### ISSUE TITLE
/friend, makes the user appear to be offline after a game invite /play

### ISSUE THREAD

**Issue by phipno** [albert2804/transendence#92]
If you first send someone a invite with /play and then a friend request with /friend and the other accepts both accounts appear to be in the offline list in the chat

**Comment by Tilmanfs95** [comment]
After a long search I could find the bug.
Problem was, that the gameHandler overwrote the customUser object with the new data for the leaderboard but the rest of the userdata wasn't actual. (in this case the chat_online field).
In the other direction the same happened when the chatconsumer overwrote the customUsers chat_online field, but hadn't the actual data for the leaderboard...
So now both gets an actual instance of the customUser object before saving something.
Important:
This is just a fix and I have to look at the rest of my code again because I am not sure if I made the same mistake somewhere else...
But for now I think its good to have a running system again ;)
